swagger: '2.0'
info:
  version: 1.0.0
  title: UGOK
host: ugok-app.herokuapp.com
schemes:
  - https
# 全てのAPIのペースになるパス。 /v1/users のようになる。
basePath: /api
produces:
  - application/json
consumes:
  - application/json
paths:
  '/users':
    get:
      description: 全ユーザの情報取得
      responses:
        '200':
          description: 成功
          schema:
            type: array
            properties:
              user:
                type: $ref: '#/definitions/User'
paths:
  '/user/{id}':
    get:
      description: ユーザごとの情報取得
      parameters:
      - name: id
        in: path
        description: MongoDBのUserID
        required: true
        type: string
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              user:
                type: $ref: '#/definitions/User'

definitions:
  User:
    type: object
    properties:
      _id: string
      name: string
      __v: integer
      twitter: $ref: '#/definitions/Twitter'
      alis: $ref: '#/definitions/Alis'
  Twitter:
    type: object
    properties:
      _id: string
      twitterId: string
      screenName: string
      icon: string
      __v: integer
      likes: $ref: '#/definitions/Data'
      rt: $ref: '#/definitions/Data'
  Alis:
    type: object
    properties:
      _id: string
      alisId: string
      __v: integer
      likes: $ref: '#/definitions/Data'
      posts: $ref: '#/definitions/Data'
  Data:
    type: object
    properties:
      all: integer
      week: integer
      half: integer