swagger: '2.0'
info:
  version: 1.0.0
  title: UGOK

paths:
  'api/users':
    get:
      description: 全ユーザの情報取得
      responses:
        '200':
          description: 成功
          schema:
            type: array
            properties:
              user:
                type: $ref: '#/definitions/User'
paths:
  'api/user/{id}':
    get:
      description: ユーザごとの情報取得
      parameters:
      - name: id
        in: path
        description: MongoDBのUserID
        required: true
        type: string
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              id:
                type: integer
              username:
                type: string

definitions:
  User:
    type: object
    properties:
      _id: string
      name: string
      twitterId: string
      __v: integer
      alisId: string