swagger: '2.0'
info:
  version: '1.0.0'
  title: 'UGOK API'
host: 'ugok-app.herokuapp.com'
schemes:
  - 'https'
# 全てのAPIのペースになるパス。 /v1/users のようになる。
basePath: '/api'
produces:
  - 'application/json'
consumes:
  - 'application/json'
paths:
  /users:
    get:
      description: '全ユーザの情報取得'
      responses:
        200:
          description: '成功'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/User'
  /user/{id}:
    get:
      description: 'ユーザごとの情報取得'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'MongoDBのUserID'
        required: true
        type: 'string'
      responses:
        200:
          description: '成功'
          schema:
            type: 'object'
            properties:
              user:
                $ref: '#/definitions/User'
definitions:
  User:
    type: 'object'
    properties:
      _id:
        type: 'string'
      name:
        type: 'string'
      __v:
        type: 'integer'
      twitter: 
        $ref: '#/definitions/Twitter'
      alis: 
        $ref: '#/definitions/Alis'
  Twitter:
    type: 'object'
    properties:
      _id:
        type: 'string'
      twitterId:
        type: 'string'
      screenName:
        type: 'string'
      icon:
        type: 'string'
      __v:
        type: 'integer'
      likes: 
        $ref: '#/definitions/Data'
      rt: 
        $ref: '#/definitions/Data'
  Alis:
    type: 'object'
    properties:
      _id:
        type: 'string'
      alisId:
        type: 'string'
      __v:
        type: 'integer'
      likes: 
        $ref: '#/definitions/Data'
      posts: 
        $ref: '#/definitions/Data'
  Data:
    type: 'object'
    properties:
      all:
        type: 'integer'
      week:
        type: 'integer'
      half:
        type: 'integer'